---
meta:
  dns_root: (( param "Please configure your root DNS name" ))
  security_groups: (( param "Please configure your AWS Security Groups" ))
  persistent_disk: 4096

  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest

jobs:
  - name: che_z1
    networks:
      - name: codenvy_che1
    persistent_disk: (( grab meta.persistent_disk ))
    properties:
      che:
        docker:
          host: tcp://127.0.0.1:2376
      docker:
        tcp_address: 127.0.0.1
        tcp_port: 2376

compilation:
  cloud_properties:
    instance_type: m3.medium

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m3.medium

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: codenvy_che1
    type: dynamic
    cloud_properties:
      security_groups: (( grab meta.security_groups ))
