---
update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  serial: false

jobs:
  - name: che_z1
    templates:
    - name: che
      release: eclipse-che
    - name: docker
      release: docker
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "Please configure the networks for this job" ))
networks: (( param "Please configure the global network definitions for this Deployment" ))

properties: {}
